version: '3.4'
services:
  jira:
    # 国内镜像  image: registry.cn-shenzhen.aliyuncs.com/fengzhao/jira-software:latest 
    image: chinafengzhao/confluence:7.9.3
    user: root
    container_name: confluence-software
    ports:
      - "8080:8080"

      - "8090:8090"
    # restart: always
    environment:
      # 反代域名
      - X_PROXY_NAME:confluence.fengzhao.com
      # 反代端口
      - X_PROXY_PORT:80
      # 反代访问协议
      - X_PROXY_SCHEME:http
      
      # - CATALINA_OPTS='-Xms4096m -Xmx8192m'  
    networks:
      - confluence
    depends_on:
      - db
    volumes:
      - /data/confluence/confluence:/var/atlassian/confluence
      - /data/confluence/logs:/opt/atlassian/confluence/logs

  db:
    image: mysql:5.7.31
    container_name: confluence-db
    networks:
      - confluence
    ports:
      - "3308:3306"
    # restart: always
    expose:
      - '3306' 
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=qhdata
      - MYSQL_USER=qhdata
      - MYSQL_PASSWORD=password
      - TZ=Asia/Shanghai
    volumes:
      -  /usr/local/mysql-confluence/conf/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      -  /usr/local/mysql-confluence/data:/var/lib/mysql

networks:
   confluence:
       name: confluence
